#!/bin/bash
# Verify and fix November documents in SECONDARY Firebase via Cloud Function
# This checks the Cloud Function logs to see what happened during seeding

set -e

SECONDARY_FUNCTION_URL="https://daily-readings-seeder-secondary-n6patcgpoa-uc.a.run.app"
PROJECT="aisaiah-sfa-dev-app"

echo "═══════════════════════════════════════════════════════════"
echo "🔍 VERIFYING NOVEMBER 2025 IN SECONDARY FIREBASE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "⚠️  Note: Due to permission restrictions, this will:"
echo "   1. Check Firebase Console manually (you need to do this)"
echo "   2. Provide commands to reseed specific date ranges"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 MANUAL VERIFICATION STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open Firebase Console:"
echo "   https://console.firebase.google.com/project/aisaiah-sfa-dev-app/firestore/data/~2Fdaily_scripture"
echo ""
echo "2. Check each November document for:"
echo "   ✅ gospel_verse should be UNIQUE for each day (not all 'John 3:16')"
echo "   ✅ body should be SHORT like 'Gospel: Luke 17:26-37'"
echo "   ✅ responsorial_psalm_verse should exist"
echo "   ✅ usccb_link should exist"
echo ""
echo "3. You mentioned Nov 1-5 are correct but days after are not"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 FIX OPTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Option 1: Fix Nov 6-30 (if 1-5 are correct)"
echo "────────────────────────────────────────────"
echo ""
echo "First, DELETE the incorrect documents via Firebase Console:"
echo "  1. Go to Firestore"
echo "  2. Select documents 2025-11-06 through 2025-11-30"
echo "  3. Click Delete"
echo ""
echo "Then, trigger reseeding via the secondary Cloud Function:"
echo ""
echo "# You need proper permissions to run this"
echo "curl -X POST \"$SECONDARY_FUNCTION_URL?start_date=2025-11-06&end_date=2025-11-30\" \\"
echo "  -H \"Authorization: bearer \$(gcloud auth print-identity-token --project=$PROJECT)\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{}'"
echo ""

echo "Option 2: Fix ALL November (complete reseed)"
echo "────────────────────────────────────────────"
echo ""
echo "1. DELETE all November documents (2025-11-01 to 2025-11-30) via Firebase Console"
echo "2. Trigger complete reseed:"
echo ""
echo "curl -X POST \"$SECONDARY_FUNCTION_URL?start_date=2025-11-01&end_date=2025-11-30\" \\"
echo "  -H \"Authorization: bearer \$(gcloud auth print-identity-token --project=$PROJECT)\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{}'"
echo ""

echo "Option 3: Fix specific date range"
echo "────────────────────────────────────────────"
echo ""
echo "Replace START and END with your dates:"
echo ""
echo "curl -X POST \"$SECONDARY_FUNCTION_URL?start_date=START&end_date=END\" \\"
echo "  -H \"Authorization: bearer \$(gcloud auth print-identity-token --project=$PROJECT)\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{}'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 CHECK CLOUD FUNCTION LOGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To see what happened during the last seeding:"
echo ""
echo "gcloud logging read \\"
echo "  \"resource.type=cloud_run_revision AND resource.labels.service_name=daily-readings-seeder-secondary\" \\"
echo "  --project=$PROJECT \\"
echo "  --limit=100 \\"
echo "  --format=\"value(textPayload)\""
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 WHAT TO LOOK FOR IN LOGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Good: \"✅ Created new document 2025-11-XX with all daily readings\""
echo "✅ Good: \"✅ Updated document 2025-11-XX with new fields\""
echo "⏭️  Skipped: \"⏭️  Document 2025-11-XX already has complete responsorial psalm\""
echo "❌ Bad: \"⚠️  Document 2025-11-XX has incorrect default data (John 3:16)\""
echo "❌ Bad: \"403 Missing or insufficient permissions\""
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 QUICK TEST: Seed a Single Day"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test with Nov 6 (first potentially bad day):"
echo ""
echo "# First delete 2025-11-06 in Firebase Console, then:"
echo ""
echo "curl -X POST \"$SECONDARY_FUNCTION_URL?start_date=2025-11-06&end_date=2025-11-06\" \\"
echo "  -H \"Authorization: bearer \$(gcloud auth print-identity-token --project=$PROJECT)\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{}'"
echo ""
echo "Then check Firebase Console to see if 2025-11-06 has correct unique data"
echo ""


