#!/bin/bash
echo "📋 WHAT YOU NEED - Quick Reference"
echo "=================================="
echo ""
echo "1️⃣  GCP PROJECT ID:"
echo "   Your options:"
gcloud projects list --format="table(projectId,name)" 2>/dev/null || echo "   (Run: gcloud projects list)"
echo ""
echo "2️⃣  GITHUB REPOSITORY:"
echo "   Your repositories:"
gh repo list --limit 10 --json nameWithOwner -q '.[].nameWithOwner' 2>/dev/null | sed 's/^/   - /' || echo "   (Run: gh repo list)"
echo ""
echo "   If you need to create one: https://github.com/new"
echo ""
echo "3️⃣  YOUTUBE API KEY:"
echo "   Get it at: https://console.cloud.google.com/apis/credentials"
echo ""
echo "4️⃣  FIREBASE SERVICE ACCOUNT KEY:"
echo "   Get it at: https://console.firebase.google.com"
echo "   Settings → Project settings → Service accounts"
echo ""
echo "📝 Full checklist: See SETUP_CHECKLIST.md"
